#!/usr/bin/env python
import traceback
import easywatch
import sh


def handler(event_type, src_path):
    print event_type, src_path 
    if event_type == "modified":
        try:
            sh.make()
        except:
            traceback.print_exc()

easywatch.watch("src", handler)
